image:
  file: .gitpod.Dockerfile

jetbrains:
  intellij:
    plugins:
      - org.intellij.scala

tasks:
  - name: base init
    init: |
      set -e
      gp env IDEPROBE_DISPLAY=xvfb
      sbt "Test / compile"
      /ide-desktop/backend/bin/remote-dev-server.sh warm-up /workspace/ide-probe
      set +e
  - name: tailscaled
    command: |
      if [ -n "${TAILSCALE_STATE_MYPROJECT}" ]; then
        # restore the tailscale state from gitpod user's env vars
        sudo mkdir -p /var/lib/tailscale
        echo "${TAILSCALE_STATE_MYPROJECT}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
      fi
      service tailscaled start
      service tailscaled status
  - name: tailscale
    command: |
      if [ -n "${TAILSCALE_STATE_MYPROJECT}" ]; then
        sudo -E tailscale up
      else
        sudo -E tailscale up --hostname "gitpod-${GITPOD_GIT_USER_NAME// /-}-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)"
        # store the tailscale state into gitpod user
        gp env TAILSCALE_STATE_MYPROJECT="$(sudo cat /var/lib/tailscale/tailscaled.state)"
      fi
