name: Update IntelliJ Version

on:
  pull_request:

jobs:
  bump-intellij-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Update default IntelliJ version
        run: |
          sbt "update-intellij / run --java-home /usr/local/openjdk-11"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if [[ -n $(git status | grep 'modified') ]]
          then
            RELEASE_LINE=$(grep 'release = \"' core/driver/sources/src/main/resources/reference.conf)
            INTELLIJ_VERSION=$(awk -F'\"|\"' '{print $2}' <<< "$RELEASE_LINE")
            git commit -m "updated default IntelliJ version to $INTELLIJ_VERSION"
            COMMIT_SHA=$(git rev-parse HEAD)
            git fetch
            git checkout $GITHUB_BASE_REF
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] \
              https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh -y
            gh repo fork --remote=true
            BRANCH_NAME="update_intellij_version_to_$INTELLIJ_VERSION"
            git branch $BRANCH_NAME
            git checkout $BRANCH_NAME
            git cherry-pick $COMMIT_SHA
            git push --set-upstream origin $BRANCH_NAME
            echo $GITHUB_TOKEN | gh auth login --with-token
            PR_TITLE="Update IntelliJ version to $INTELLIJ_VERSION"
            SCALA_PLUGIN_FILE_URL="https://github.com/VirtusLab/ide-probe/blob/master/extensions/scala/tests/src/test/resources/scala.conf"
            SCALA_PLUGIN_VERSIONS_URL="https://plugins.jetbrains.com/plugin/1347-scala/versions"
            PR_BODY="Updates the default IntelliJ Version to the newest release. \
              Please, check currently used version of the scala plugin: $SCALA_PLUGIN_FILE_URL \
              and verify if it is compatible with the new intelliJ IDEA version ($INTELLIJ_VERSION) here: $SCALA_PLUGIN_VERSIONS_URL. \
              If the version of the scala plugin used in $SCALA_PLUGIN_FILE_URL is NOT compatible - please update it in a separate commit."
            gh pr create --title $PR_TITLE --body $PR_BODY
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
